# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IM_MSA_Transformer": "00_core.ipynb",
         "gen_MSAs": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://damiano-sg.github.io/Iterative_masking/"

git_url = "https://github.com/damiano-sg/Iterative_masking/tree/main/"

def custom_doc_links(name): return None
