# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://damiano-sg.github.io/Iterative_masking/"

git_url = "https://github.com/damiano-sg/Iterative_masking/tree/main/"

def custom_doc_links(name): return None
